# -*- coding: utf-8 -*-
"""laccase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P7zVsrGKg6isTfpUSlz49iRjHWt-4pl1
"""

!pip install transformers torch pandas
import torch
from transformers import EsmForMaskedLM, EsmTokenizer
import pandas as pd
import numpy as np

print("Loading Meta's ESM-2 Model, please wait...")
model_name = "facebook/esm2_t6_8M_UR50D"
tokenizer = EsmTokenizer.from_pretrained(model_name)
model = EsmForMaskedLM.from_pretrained(model_name)

target_sequence = "AIGPTADLVISINPAAPLTVNPADLVISINPAQLTVNPA"
print(f"Analyzing Sequence: {target_sequence}")

def predict_mutations(sequence):
    results = []
    inputs = tokenizer(sequence, return_tensors="pt")
    with torch.no_grad():
        logits = model(**inputs).logits

    for i in range(1, len(sequence) + 1):  # +1 because of start token
        original_aa = sequence[i-1]
        probs = torch.nn.functional.softmax(logits[0,i], dim=-1)
        top_probs, top_indices = torch.topk(probs, 5)  # Get top 5 suggestions

        for score, idx in zip(top_probs, top_indices):
            predicted_aa = tokenizer.decode([idx])
            if predicted_aa not in ['<cls>', '<sep>', '<pad>', '<unk>', '<mask>', original_aa]:
                mutant_seq = list(sequence)
                mutant_seq[i-1] = predicted_aa
                mutant_seq = "".join(mutant_seq)
                results.append({
                    'Position': i,
                    'Original': original_aa,
                    'Mutation': predicted_aa,
                    'AI_Confidence_Score': float(score),
                    'Full_Sequence': mutant_seq
                })
    return pd.DataFrame(results)

print("AI is thinking... (Predicting stable mutations)")
df_predictions = predict_mutations(target_sequence)
top_candidates = df_predictions.sort_values(by='AI_Confidence_Score', ascending=False).head(20)

print("\n" + "="*60)
print(" REAL RESULTS GENERATED")
print("These are the top 20 mutations the AI predicts will be structurally stable.")
print("="*60)
print(top_candidates[['Position', 'Original', 'Mutation', 'AI_Confidence_Score']])

filename = "laccase_ai_candidates.csv"
top_candidates.to_csv(filename, index=False)
print(f"\nFile saved: {filename}")
print("You can download this CSV from the Colab file folder")
from google.colab import files
files.download(filename)